/**
 * ENEMY DEFINITIONS
 * Defines the stats and animation data for every enemy type in the game.
 */
const Enemy = {

    GalaxyDragon: {
        folderName: 'Galaxy Dragon',
        size: 3200,
        healthMax: 50,
        moveSpeed: 18,
        archMoveSpeed: 17,
        godMoveSpeed: 20,
        alphaMoveSpeed: 25,
        omegaMoveSpeed: 35,
        spacing: 200,
        startDist: 50000,
        attackRange: 5000,
        archAttackRange: 10000,
        godAttackRange: 15000,
        alphaAttackRange: 20000,
        omegaAttackRange: 30000,
        damageMin: 10,
        damageMax: 30,
        walkPath: 'img/Enemies/Galaxy Dragon/Galaxy Dragon Flying Forward/Spritesheet/512x512/Galaxy Dragon Flying Forward_512x512_sheet.png',
        deathPath: 'img/Enemies/Galaxy Dragon/Galaxy Dragon Death/Spritesheet/512x512/Galaxy Dragon Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Galaxy Dragon/Galaxy Dragon Attack/Spritesheet/512x512/Galaxy Dragon Attack_512x512_sheet.png',
        walkFrames: 53, deathFrames: 145, attackFrames: 13,
        walkCols: 8, deathCols: 13, attackCols: 4,
        walkSize: 512, deathSize: 512, attackSize: 512,
        walkAnimSpeed: 0.02, attackAnimSpeed: 1.0, deathAnimSpeed: 1.0,
        archWalkAnimSpeed: 0.05, archAttackAnimSpeed: 2.5, archDeathAnimSpeed: 2.5,
        godWalkAnimSpeed: 0.07, godAttackAnimSpeed: 3.5, godDeathAnimSpeed: 3.5,
        alphaWalkAnimSpeed: 0.1, alphaAttackAnimSpeed: 5.0, alphaDeathAnimSpeed: 5.0,
        omegaWalkAnimSpeed: 0.15, omegaAttackAnimSpeed: 8.0, omegaDeathAnimSpeed: 8.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Dragon',
        chargeSpeed: 250,
        archChargeSpeed: 500,
        godChargeSpeed: 1000,
        alphaChargeSpeed: 2500,
        omegaChargeSpeed: 6000,
        chargeDistanceMult: 1.5,
        archChargeDistanceMult: 2,
        godChargeDistanceMult: 4,
        alphaChargeDistanceMult: 8,
        omegaChargeDistanceMult: 15
    },
    PhoenixSurrender: {
        folderName: 'Phoenix Surrender',
        size: 3000,
        healthMax: 85,
        moveSpeed: 16,
        archMoveSpeed: 32,
        godMoveSpeed: 40,
        alphaMoveSpeed: 55,
        omegaMoveSpeed: 75,
        spacing: 180,
        startDist: 50000,
        attackRange: 9000,
        archAttackRange: 18000,
        godAttackRange: 25000,
        alphaAttackRange: 40000,
        omegaAttackRange: 60000,
        damageMin: 25,
        damageMax: 70,
        walkPath: 'img/Enemies/Phoenix Surrender/Surrender Flying Forward/Spritesheet/512x512/Surrender Flying Forward_512x512_sheet.png',
        deathPath: 'img/Enemies/Phoenix Surrender/Surrender Death/Spritesheet/512x512/Surrender Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Phoenix Surrender/Surrender Attack/Spritesheet/512x512/Surrender Attack_512x512_sheet.png',
        walkFrames: 23, deathFrames: 145, attackFrames: 84,
        walkCols: 5, deathCols: 13, attackCols: 10,
        walkSize: 512, deathSize: 512, attackSize: 512,
        walkAnimSpeed: 0.03, attackAnimSpeed: 2.0, deathAnimSpeed: 1.5,
        archWalkAnimSpeed: 0.075, archAttackAnimSpeed: 5.0, archDeathAnimSpeed: 3.75,
        godWalkAnimSpeed: 0.1, godAttackAnimSpeed: 7.0, godDeathAnimSpeed: 5.0,
        alphaWalkAnimSpeed: 0.15, alphaAttackAnimSpeed: 10.0, alphaDeathAnimSpeed: 8.0,
        omegaWalkAnimSpeed: 0.2, omegaAttackAnimSpeed: 15.0, omegaDeathAnimSpeed: 12.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Phoenix',
        chargeSpeed: 300,
        archChargeSpeed: 600,
        godChargeSpeed: 1200,
        alphaChargeSpeed: 3000,
        omegaChargeSpeed: 8000,
        chargeDistanceMult: 1.5,
        archChargeDistanceMult: 2,
        godChargeDistanceMult: 4,
        alphaChargeDistanceMult: 10,
        omegaChargeDistanceMult: 20
    },
    BlueDragon: {
        folderName: 'Blue Dragon',
        size: 3500,
        healthMax: 120,
        moveSpeed: 14,
        archMoveSpeed: 28,
        godMoveSpeed: 35,
        alphaMoveSpeed: 50,
        omegaMoveSpeed: 70,
        spacing: 250,
        startDist: 60000,
        attackRange: 2200,
        archAttackRange: 4400,
        godAttackRange: 9000,
        alphaAttackRange: 20000,
        omegaAttackRange: 40000,
        damageMin: 40,
        damageMax: 90,
        walkPath: 'img/Enemies/Blue Dragon/Blue Dragon Flying Forward/Spritesheet/1024x1024/Blue Dragon Flying Forward_1024x1024_sheet.png',
        deathPath: 'img/Enemies/Blue Dragon/Blue Dragon Death/Spritesheet/512x512/Blue Dragon Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Blue Dragon/Blue Dragon Attack/Spritesheet/512x512/Blue Dragon Attack_512x512_sheet.png',
        walkFrames: 32, deathFrames: 138, attackFrames: 90,
        walkCols: 6, deathCols: 12, attackCols: 10,
        walkSize: 1024, deathSize: 512, attackSize: 512,
        walkAnimSpeed: 0.025, attackAnimSpeed: 1.8, deathAnimSpeed: 1.2,
        archWalkAnimSpeed: 0.0625, archAttackAnimSpeed: 4.5, archDeathAnimSpeed: 3.0,
        godWalkAnimSpeed: 0.09, godAttackAnimSpeed: 6.0, godDeathAnimSpeed: 4.5,
        alphaWalkAnimSpeed: 0.12, alphaAttackAnimSpeed: 9.0, alphaDeathAnimSpeed: 6.0,
        omegaWalkAnimSpeed: 0.18, omegaAttackAnimSpeed: 15.0, omegaDeathAnimSpeed: 10.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Dragon',
        chargeSpeed: 200,
        archChargeSpeed: 400,
        godChargeSpeed: 900,
        alphaChargeSpeed: 2200,
        omegaChargeSpeed: 5500,
        chargeDistanceMult: 25,
        archChargeDistanceMult: 50,
        godChargeDistanceMult: 100,
        alphaChargeDistanceMult: 200,
        omegaChargeDistanceMult: 400
    },
    BlackRedButterfly: {
        folderName: 'Black Red Butterfly',
        size: 2800,
        healthMax: 60,
        moveSpeed: 17,
        archMoveSpeed: 34,
        godMoveSpeed: 42,
        alphaMoveSpeed: 55,
        omegaMoveSpeed: 80,
        spacing: 150,
        startDist: 40000,
        attackRange: 4000,
        archAttackRange: 8000,
        godAttackRange: 13000,
        alphaAttackRange: 25000,
        omegaAttackRange: 45000,
        damageMin: 15,
        damageMax: 35,
        walkPath: 'img/Enemies/Black Red Butterfly/Black Red Butterfly Flying Forward/Spritesheet/1024x1024/Black Red Butterfly Flying Forward_1024x1024_sheet.png',
        deathPath: 'img/Enemies/Butterfly Death/Spritesheet/512x512/Butterfly Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Black Red Butterfly/Black Red Butterfly Attacking Forward/Spritesheet/1024x1024/Black Red Butterfly Attacking Forward_1024x1024_sheet.png',
        walkFrames: 19, deathFrames: 75, attackFrames: 13,
        walkCols: 5, deathCols: 9, attackCols: 4,
        walkSize: 1024, deathSize: 512, attackSize: 1024,
        walkAnimSpeed: 0.03, attackAnimSpeed: 1.5, deathAnimSpeed: 1.0,
        archWalkAnimSpeed: 0.075, archAttackAnimSpeed: 3.75, archDeathAnimSpeed: 2.5,
        godWalkAnimSpeed: 0.1, godAttackAnimSpeed: 5.0, godDeathAnimSpeed: 3.5,
        alphaWalkAnimSpeed: 0.13, alphaAttackAnimSpeed: 7.0, alphaDeathAnimSpeed: 4.5,
        omegaWalkAnimSpeed: 0.18, omegaAttackAnimSpeed: 10.0, omegaDeathAnimSpeed: 6.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Butterfly',
        chargeSpeed: 250,
        archChargeSpeed: 500,
        godChargeSpeed: 1000,
        alphaChargeSpeed: 2500,
        omegaChargeSpeed: 5500,
        chargeDistanceMult: 1.5,
        archChargeDistanceMult: 3,
        godChargeDistanceMult: 6,
        alphaChargeDistanceMult: 12,
        omegaChargeDistanceMult: 24
    },
    BlueWhiteButterfly: {
        folderName: 'Blue White Butterfly',
        size: 3000,
        healthMax: 70,
        moveSpeed: 16,
        archMoveSpeed: 32,
        godMoveSpeed: 40,
        alphaMoveSpeed: 55,
        omegaMoveSpeed: 80,
        spacing: 180,
        startDist: 45000,
        attackRange: 4500,
        archAttackRange: 9000,
        godAttackRange: 15000,
        alphaAttackRange: 30000,
        omegaAttackRange: 50000,
        damageMin: 20,
        damageMax: 45,
        walkPath: 'img/Enemies/Blue White Butterfly/Blue White Butterfly Flying Forward/Spritesheet/1024x1024/Blue White Butterfly Flying Forward_1024x1024_sheet.png',
        deathPath: 'img/Enemies/Butterfly Death/Spritesheet/512x512/Butterfly Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Blue White Butterfly/Blue Butterfly Attacking Forward/Spritesheet/1024x1024/Blue Butterfly Attacking Forward_1024x1024_sheet.png',
        walkFrames: 32, deathFrames: 75, attackFrames: 30,
        walkCols: 6, deathCols: 9, attackCols: 6,
        walkSize: 1024, deathSize: 512, attackSize: 1024,
        walkAnimSpeed: 0.03, attackAnimSpeed: 2.0, deathAnimSpeed: 1.0,
        archWalkAnimSpeed: 0.075, archAttackAnimSpeed: 5.0, archDeathAnimSpeed: 2.5,
        godWalkAnimSpeed: 0.1, godAttackAnimSpeed: 7.0, godDeathAnimSpeed: 3.5,
        alphaWalkAnimSpeed: 0.13, alphaAttackAnimSpeed: 9.0, alphaDeathAnimSpeed: 4.5,
        omegaWalkAnimSpeed: 0.18, omegaAttackAnimSpeed: 13.0, omegaDeathAnimSpeed: 6.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Butterfly',
        chargeSpeed: 280,
        archChargeSpeed: 560,
        godChargeSpeed: 1100,
        alphaChargeSpeed: 2800,
        omegaChargeSpeed: 6500,
        chargeDistanceMult: 1.8,
        archChargeDistanceMult: 3.6,
        godChargeDistanceMult: 7,
        alphaChargeDistanceMult: 15,
        omegaChargeDistanceMult: 30
    },
    GoldButterfly: {
        folderName: 'Gold Butterfly',
        size: 3200,
        healthMax: 90,
        moveSpeed: 15,
        archMoveSpeed: 30,
        godMoveSpeed: 38,
        alphaMoveSpeed: 52,
        omegaMoveSpeed: 75,
        spacing: 200,
        startDist: 50000,
        attackRange: 3000,
        archAttackRange: 6000,
        godAttackRange: 11000,
        alphaAttackRange: 22000,
        omegaAttackRange: 42000,
        damageMin: 30,
        damageMax: 60,
        walkPath: 'img/Enemies/Gold Butterfly/Gold Butterfly Flying Forward/Spritesheet/1024x1024/Gold Butterfly Flying Forward_1024x1024_sheet.png',
        deathPath: 'img/Enemies/Butterfly Death/Spritesheet/512x512/Butterfly Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Gold Butterfly/Gold Butterfly Attacking Forward/Spritesheet/1024x1024/Gold Butterfly Attacking Forward_1024x1024_sheet.png',
        walkFrames: 18, deathFrames: 75, attackFrames: 15,
        walkCols: 5, deathCols: 9, attackCols: 4,
        walkSize: 1024, deathSize: 512, attackSize: 1024,
        walkAnimSpeed: 0.025, attackAnimSpeed: 1.8, deathAnimSpeed: 1.0,
        archWalkAnimSpeed: 0.0625, archAttackAnimSpeed: 4.5, archDeathAnimSpeed: 2.5,
        godWalkAnimSpeed: 0.08, godAttackAnimSpeed: 6.0, godDeathAnimSpeed: 3.5,
        alphaWalkAnimSpeed: 0.1, alphaAttackAnimSpeed: 8.0, alphaDeathAnimSpeed: 4.5,
        omegaWalkAnimSpeed: 0.15, omegaAttackAnimSpeed: 12.0, omegaDeathAnimSpeed: 6.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Butterfly',
        chargeSpeed: 220,
        archChargeSpeed: 440,
        godChargeSpeed: 880,
        alphaChargeSpeed: 2200,
        omegaChargeSpeed: 5000,
        chargeDistanceMult: 1.2,
        archChargeDistanceMult: 2.4,
        godChargeDistanceMult: 5,
        alphaChargeDistanceMult: 10,
        omegaChargeDistanceMult: 20
    },
    GreenBlackButterfly: {
        folderName: 'Green Black Butterfly',
        size: 3400,
        healthMax: 110,
        moveSpeed: 14,
        archMoveSpeed: 28,
        godMoveSpeed: 35,
        alphaMoveSpeed: 48,
        omegaMoveSpeed: 68,
        spacing: 220,
        startDist: 55000,
        attackRange: 2500,
        archAttackRange: 5000,
        godAttackRange: 10000,
        alphaAttackRange: 20000,
        omegaAttackRange: 38000,
        damageMin: 40,
        damageMax: 80,
        walkPath: 'img/Enemies/Green Black Butterfly/Green Black Butterfly Flying Forward/Spritesheet/1024x1024/Green Black Butterfly Flying Forward_1024x1024_sheet.png',
        deathPath: 'img/Enemies/Butterfly Death/Spritesheet/512x512/Butterfly Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Green Black Butterfly/Green Black Butterfly Attacking Forward/Spritesheet/1024x1024/Green Black Butterfly Attacking Forward_1024x1024_sheet.png',
        walkFrames: 52, deathFrames: 75, attackFrames: 21,
        walkCols: 8, deathCols: 9, attackCols: 5,
        walkSize: 1024, deathSize: 512, attackSize: 1024,
        walkAnimSpeed: 0.02, attackAnimSpeed: 1.6, deathAnimSpeed: 1.0,
        archWalkAnimSpeed: 0.05, archAttackAnimSpeed: 4.0, archDeathAnimSpeed: 2.5,
        godWalkAnimSpeed: 0.07, godAttackAnimSpeed: 5.5, godDeathAnimSpeed: 3.5,
        alphaWalkAnimSpeed: 0.1, alphaAttackAnimSpeed: 7.5, alphaDeathAnimSpeed: 4.5,
        omegaWalkAnimSpeed: 0.15, omegaAttackAnimSpeed: 11.0, omegaDeathAnimSpeed: 6.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Butterfly',
        chargeSpeed: 200,
        archChargeSpeed: 400,
        godChargeSpeed: 800,
        alphaChargeSpeed: 2000,
        omegaChargeSpeed: 4500,
        chargeDistanceMult: 2.0,
        archChargeDistanceMult: 4.0,
        godChargeDistanceMult: 8,
        alphaChargeDistanceMult: 16,
        omegaChargeDistanceMult: 32
    },
    GalaxyButterfly: {
        folderName: 'Galaxy Butterfly',
        size: 3800,
        healthMax: 150,
        moveSpeed: 13,
        archMoveSpeed: 26,
        godMoveSpeed: 32,
        alphaMoveSpeed: 45,
        omegaMoveSpeed: 65,
        spacing: 250,
        startDist: 60000,
        attackRange: 2000,
        archAttackRange: 4000,
        godAttackRange: 8000,
        alphaAttackRange: 15000,
        omegaAttackRange: 30000,
        damageMin: 50,
        damageMax: 100,
        walkPath: 'img/Enemies/Galaxy Butterfly/Galaxy Butterfly Flying Forward/Spritesheet/1024x1024/Galaxy Butterfly Flying Forward_1024x1024_sheet.png',
        deathPath: 'img/Enemies/Butterfly Death/Spritesheet/512x512/Butterfly Death_512x512_sheet.png',
        attackPath: 'img/Enemies/Galaxy Butterfly/Galaxy Butterfly Attacking Forward/Spritesheet/1024x1024/Galaxy Butterfly Attacking Forward_1024x1024_sheet.png',
        walkFrames: 42, deathFrames: 75, attackFrames: 57,
        walkCols: 7, deathCols: 9, attackCols: 8,
        walkSize: 1024, deathSize: 512, attackSize: 1024,
        walkAnimSpeed: 0.015, attackAnimSpeed: 2.5, deathAnimSpeed: 1.0,
        archWalkAnimSpeed: 0.0375, archAttackAnimSpeed: 6.25, archDeathAnimSpeed: 2.5,
        godWalkAnimSpeed: 0.05, godAttackAnimSpeed: 8.5, godDeathAnimSpeed: 3.5,
        alphaWalkAnimSpeed: 0.08, alphaAttackAnimSpeed: 11.0, alphaDeathAnimSpeed: 4.5,
        omegaWalkAnimSpeed: 0.12, omegaAttackAnimSpeed: 15.0, omegaDeathAnimSpeed: 6.0,
        baseRotation: Math.PI / 2,
        isSideways: false,
        enemyType: 'Butterfly',
        chargeSpeed: 180,
        archChargeSpeed: 360,
        godChargeSpeed: 720,
        alphaChargeSpeed: 1800,
        omegaChargeSpeed: 4000,
        chargeDistanceMult: 2.5,
        archChargeDistanceMult: 5.0,
        godChargeDistanceMult: 10,
        alphaChargeDistanceMult: 20,
        omegaChargeDistanceMult: 40
    }
};
